remove destroy

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -608,7 +608,7 @@ jobs:
             fi
             
             terraform init
-            if terraform apply --auto-approve \
+            terraform apply --auto-approve \
               -var="ssh_key_value=${PRIVATE_KEY}" -var="github_test_repo=${{env.CWA_GITHUB_TEST_REPO_URL}}" \
               -var="test_name=${{ matrix.arrays.os }}" \
               -var="cwa_github_sha=${GITHUB_SHA}" -var="install_agent=${{ matrix.arrays.installAgentCommand }}" \
@@ -623,19 +623,35 @@ jobs:
               -var="s3_bucket=${S3_INTEGRATION_BUCKET}" \
               -var="plugin_tests='${{ github.event.inputs.plugins }}'" \
               -var="ssh_key_name=${KEY_NAME}" \
-              -var="test_dir=${{ matrix.arrays.test_dir }}" ; then terraform destroy -auto-approve
-            else
-              terraform destroy -auto-approve && exit 1
-            fi
+              -var="test_dir=${{ matrix.arrays.test_dir }}"
+            # if terraform apply --auto-approve \
+            #   -var="ssh_key_value=${PRIVATE_KEY}" -var="github_test_repo=${{env.CWA_GITHUB_TEST_REPO_URL}}" \
+            #   -var="test_name=${{ matrix.arrays.os }}" \
+            #   -var="cwa_github_sha=${GITHUB_SHA}" -var="install_agent=${{ matrix.arrays.installAgentCommand }}" \
+            #   -var="github_test_repo_branch=${{env.CWA_GITHUB_TEST_REPO_BRANCH}}" \
+            #   -var="ec2_instance_type=${{ matrix.arrays.instanceType }}" \
+            #   -var="user=${{ matrix.arrays.username }}" \
+            #   -var="ami=${{ matrix.arrays.ami }}" \
+            #   -var="ca_cert_path=${{ matrix.arrays.caCertPath }}" \
+            #   -var="arc=${{ matrix.arrays.arc }}" \
+            #   -var="binary_name=${{ matrix.arrays.binaryName }}" \
+            #   -var="local_stack_host_name=${{ needs.StartLocalStack.outputs.local_stack_host_name }}" \
+            #   -var="s3_bucket=${S3_INTEGRATION_BUCKET}" \
+            #   -var="plugin_tests='${{ github.event.inputs.plugins }}'" \
+            #   -var="ssh_key_name=${KEY_NAME}" \
+            #   -var="test_dir=${{ matrix.arrays.test_dir }}" ; then terraform destroy -auto-approve
+            # else
+            #   terraform destroy -auto-approve && exit 1
+            # fi
       #This is here just in case workflow cancel
-      - name: Terraform destroy
-        if: ${{ cancelled() || failure() }}
-        uses: nick-fields/retry@v2
-        with:
-          max_attempts: 3
-          timeout_minutes: 8
-          retry_wait_seconds: 5
-          command: cd terraform/ec2/linux && terraform destroy --auto-approve
+      # - name: Terraform destroy
+      #   if: ${{ cancelled() || failure() }}
+      #   uses: nick-fields/retry@v2
+      #   with:
+      #     max_attempts: 3
+      #     timeout_minutes: 8
+      #     retry_wait_seconds: 5
+      #     command: cd terraform/ec2/linux && terraform destroy --auto-approve
 
 #  EC2UserDataIntegrationTest:
 #    needs: [MakeBinary, StartLocalStack, GenerateTestMatrix]
