add fips test and support target os with test generator

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -10,7 +10,7 @@ env:
   ECR_INTEGRATION_TEST_REPO: "cwagent-integration-test"
   CWA_GITHUB_TEST_REPO_NAME: "movence/amazon-cloudwatch-agent-test"
   CWA_GITHUB_TEST_REPO_URL: "https://github.com/movence/amazon-cloudwatch-agent-test.git"
-  CWA_GITHUB_TEST_REPO_BRANCH: "migration-restart"
+  CWA_GITHUB_TEST_REPO_BRANCH: "migration-fips"
 
 on:
   push:
@@ -186,65 +186,65 @@ jobs:
           echo "eks_daemon_matrix: ${{ steps.set-matrix.outputs.eks_daemon_matrix }}"
           echo "eks_deployment_matrix: ${{ steps.set-matrix.outputs.eks_deployment_matrix }}"
 
-  MakeMSIZip:
-    name: 'MakeMSIZip'
-    runs-on: ubuntu-latest
-    needs: [MakeBinary]
-    permissions:
-      id-token: write
-      contents: read
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          repository: ${{env.CWA_GITHUB_TEST_REPO_NAME}}
-
-      - name: Set up Go 1.x
-        uses: actions/setup-go@v4
-        with:
-          go-version: ~1.19.6
-
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
-          aws-region: us-west-2
-
-      - name: Cache win zip
-        id: cached_win_zip
-        uses: actions/cache@v3
-        with:
-          key: "cached_win_zip_${{ github.sha }}"
-          path: go.mod
-
-      - name: Copy binary
-        if: steps.cached_win_zip.outputs.cache-hit != 'true'
-        run: |
-          aws s3 cp s3://${S3_INTEGRATION_BUCKET}/integration-test/binary/${{ github.sha }} . --recursive
-      - name: Unzip
-        if: steps.cached_win_zip.outputs.cache-hit != 'true'
-        run: |
-          sudo apt install unzip
-          unzip windows/amd64/amazon-cloudwatch-agent.zip -d windows-agent
-      - name: Create msi dep folder and copy deps
-        if: steps.cached_win_zip.outputs.cache-hit != 'true'
-        run: |
-          export version=$(cat CWAGENT_VERSION)
-          echo cw agent version $version
-          mkdir msi_dep
-          cp -r msi/tools/. msi_dep/
-          cp -r windows-agent/amazon-cloudwatch-agent/. msi_dep/
-          go run msi/tools/msiversion/msiversionconverter.go $version msi_dep/amazon-cloudwatch-agent.wxs '<version>' 
-          go run msi/tools/msiversion/msiversionconverter.go $version msi_dep/manifest.json __VERSION__ 
-
-      - name: Zip
-        if: steps.cached_win_zip.outputs.cache-hit != 'true'
-        run: |
-          sudo apt install zip
-          zip buildMSI.zip msi_dep/*
-
-      - name: Upload zip
-        if: steps.cached_win_zip.outputs.cache-hit != 'true'
-        run: aws s3 cp buildMSI.zip s3://${S3_INTEGRATION_BUCKET}/integration-test/packaging/${{ github.sha }}/buildMSI.zip
+#  MakeMSIZip:
+#    name: 'MakeMSIZip'
+#    runs-on: ubuntu-latest
+#    needs: [MakeBinary]
+#    permissions:
+#      id-token: write
+#      contents: read
+#    steps:
+#      - uses: actions/checkout@v3
+#        with:
+#          repository: ${{env.CWA_GITHUB_TEST_REPO_NAME}}
+#
+#      - name: Set up Go 1.x
+#        uses: actions/setup-go@v4
+#        with:
+#          go-version: ~1.19.6
+#
+#      - name: Configure AWS Credentials
+#        uses: aws-actions/configure-aws-credentials@v2
+#        with:
+#          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
+#          aws-region: us-west-2
+#
+#      - name: Cache win zip
+#        id: cached_win_zip
+#        uses: actions/cache@v3
+#        with:
+#          key: "cached_win_zip_${{ github.sha }}"
+#          path: go.mod
+#
+#      - name: Copy binary
+#        if: steps.cached_win_zip.outputs.cache-hit != 'true'
+#        run: |
+#          aws s3 cp s3://${S3_INTEGRATION_BUCKET}/integration-test/binary/${{ github.sha }} . --recursive
+#      - name: Unzip
+#        if: steps.cached_win_zip.outputs.cache-hit != 'true'
+#        run: |
+#          sudo apt install unzip
+#          unzip windows/amd64/amazon-cloudwatch-agent.zip -d windows-agent
+#      - name: Create msi dep folder and copy deps
+#        if: steps.cached_win_zip.outputs.cache-hit != 'true'
+#        run: |
+#          export version=$(cat CWAGENT_VERSION)
+#          echo cw agent version $version
+#          mkdir msi_dep
+#          cp -r msi/tools/. msi_dep/
+#          cp -r windows-agent/amazon-cloudwatch-agent/. msi_dep/
+#          go run msi/tools/msiversion/msiversionconverter.go $version msi_dep/amazon-cloudwatch-agent.wxs '<version>'
+#          go run msi/tools/msiversion/msiversionconverter.go $version msi_dep/manifest.json __VERSION__
+#
+#      - name: Zip
+#        if: steps.cached_win_zip.outputs.cache-hit != 'true'
+#        run: |
+#          sudo apt install zip
+#          zip buildMSI.zip msi_dep/*
+#
+#      - name: Upload zip
+#        if: steps.cached_win_zip.outputs.cache-hit != 'true'
+#        run: aws s3 cp buildMSI.zip s3://${S3_INTEGRATION_BUCKET}/integration-test/packaging/${{ github.sha }}/buildMSI.zip
 
   # MakeMacPkg:
   #   name: 'MakeMacPkg'
@@ -321,44 +321,44 @@ jobs:
   #         cd arm64
   #         ./create_pkg.sh ${{ secrets.S3_INTEGRATION_BUCKET }} ${{ github.sha }} arm64
 
-  BuildMSI:
-    name: 'BuildMSI'
-    runs-on: windows-latest
-    needs: [MakeMSIZip]
-    permissions:
-      id-token: write
-      contents: read
-    steps:
-      - uses: actions/checkout@v3
-
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
-          aws-region: us-west-2
-
-      - name: Cache msi
-        id: cached_msi
-        uses: actions/cache@v3
-        with:
-          key: "cached_msi_${{ github.sha }}"
-          path: go.mod
-
-      # Using the env variable returns "" for bucket name thus use the secret
-      - name: Copy msi
-        if: steps.cached_msi.outputs.cache-hit != 'true'
-        run: aws s3 cp s3://${{ secrets.S3_INTEGRATION_BUCKET }}/integration-test/packaging/${{ github.sha }}/buildMSI.zip .
-
-      - name: Create msi
-        if: steps.cached_msi.outputs.cache-hit != 'true'
-        run : |
-          curl -OLS https://github.com/wixtoolset/wix3/releases/download/wix3111rtm/wix311.exe
-          .\wix311.exe /install /quiet /norestart
-          $wixToolsetBinPath = ";C:\Program Files (x86)\WiX Toolset v3.11\bin;"
-          $env:PATH = $env:PATH + $wixToolsetBinPath
-          Expand-Archive buildMSI.zip -Force
-          cd buildMSI/msi_dep
-          .\create_msi.ps1 ${{ github.sha }} ${{ secrets.S3_INTEGRATION_BUCKET }}
+#  BuildMSI:
+#    name: 'BuildMSI'
+#    runs-on: windows-latest
+#    needs: [MakeMSIZip]
+#    permissions:
+#      id-token: write
+#      contents: read
+#    steps:
+#      - uses: actions/checkout@v3
+#
+#      - name: Configure AWS Credentials
+#        uses: aws-actions/configure-aws-credentials@v2
+#        with:
+#          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
+#          aws-region: us-west-2
+#
+#      - name: Cache msi
+#        id: cached_msi
+#        uses: actions/cache@v3
+#        with:
+#          key: "cached_msi_${{ github.sha }}"
+#          path: go.mod
+#
+#      # Using the env variable returns "" for bucket name thus use the secret
+#      - name: Copy msi
+#        if: steps.cached_msi.outputs.cache-hit != 'true'
+#        run: aws s3 cp s3://${{ secrets.S3_INTEGRATION_BUCKET }}/integration-test/packaging/${{ github.sha }}/buildMSI.zip .
+#
+#      - name: Create msi
+#        if: steps.cached_msi.outputs.cache-hit != 'true'
+#        run : |
+#          curl -OLS https://github.com/wixtoolset/wix3/releases/download/wix3111rtm/wix311.exe
+#          .\wix311.exe /install /quiet /norestart
+#          $wixToolsetBinPath = ";C:\Program Files (x86)\WiX Toolset v3.11\bin;"
+#          $env:PATH = $env:PATH + $wixToolsetBinPath
+#          Expand-Archive buildMSI.zip -Force
+#          cd buildMSI/msi_dep
+#          .\create_msi.ps1 ${{ github.sha }} ${{ secrets.S3_INTEGRATION_BUCKET }}
 
   #GH actions set up gpg only works on ubuntu as of this commit date
   # GPGSignMacAndWindowsPackage:
@@ -409,49 +409,49 @@ jobs:
   #         aws s3 cp packages/amd64/amazon-cloudwatch-agent.pkg.sig s3://${S3_INTEGRATION_BUCKET}/integration-test/packaging/${{ github.sha }}/amd64/amazon-cloudwatch-agent.pkg.sig
   #         aws s3 cp packages/arm64/amazon-cloudwatch-agent.pkg.sig s3://${S3_INTEGRATION_BUCKET}/integration-test/packaging/${{ github.sha }}/arm64/amazon-cloudwatch-agent.pkg.sig
   
-  StartLocalStack:
-    name: 'StartLocalStack'
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: terraform/ec2/localstack
-    outputs:
-      local_stack_host_name: ${{ steps.localstack.outputs.local_stack_host_name }}
-    permissions:
-      id-token: write
-      contents: read
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          repository: ${{env.CWA_GITHUB_TEST_REPO_NAME}}
-          ref: ${{env.CWA_GITHUB_TEST_REPO_BRANCH}}
-
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
-          aws-region: us-west-2
-
-      - name: Verify Terraform version
-        run: terraform --version
-
-      - name: Terraform init
-        run: terraform init
-
-      - name: Terraform apply
-        id: localstack
-        run: >
-          echo run terraform and execute test code &&
-          terraform apply --auto-approve
-          -var="ssh_key_value=${PRIVATE_KEY}"
-          -var="github_test_repo=${{env.CWA_GITHUB_TEST_REPO_URL}}"
-          -var="cwa_github_sha=${GITHUB_SHA}"
-          -var="s3_bucket=${S3_INTEGRATION_BUCKET}"
-          -var="ssh_key_name=${KEY_NAME}" &&
-          LOCAL_STACK_HOST_NAME=$(terraform output -raw public_dns) &&
-          echo $LOCAL_STACK_HOST_NAME &&
-          echo "::set-output name=local_stack_host_name::$LOCAL_STACK_HOST_NAME" &&
-          aws s3 cp terraform.tfstate s3://${S3_INTEGRATION_BUCKET}/integration-test/local-stack-terraform-state/${GITHUB_SHA}/terraform.tfstate
+#  StartLocalStack:
+#    name: 'StartLocalStack'
+#    runs-on: ubuntu-latest
+#    defaults:
+#      run:
+#        working-directory: terraform/ec2/localstack
+#    outputs:
+#      local_stack_host_name: ${{ steps.localstack.outputs.local_stack_host_name }}
+#    permissions:
+#      id-token: write
+#      contents: read
+#    steps:
+#      - uses: actions/checkout@v3
+#        with:
+#          repository: ${{env.CWA_GITHUB_TEST_REPO_NAME}}
+#          ref: ${{env.CWA_GITHUB_TEST_REPO_BRANCH}}
+#
+#      - name: Configure AWS Credentials
+#        uses: aws-actions/configure-aws-credentials@v2
+#        with:
+#          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
+#          aws-region: us-west-2
+#
+#      - name: Verify Terraform version
+#        run: terraform --version
+#
+#      - name: Terraform init
+#        run: terraform init
+#
+#      - name: Terraform apply
+#        id: localstack
+#        run: >
+#          echo run terraform and execute test code &&
+#          terraform apply --auto-approve
+#          -var="ssh_key_value=${PRIVATE_KEY}"
+#          -var="github_test_repo=${{env.CWA_GITHUB_TEST_REPO_URL}}"
+#          -var="cwa_github_sha=${GITHUB_SHA}"
+#          -var="s3_bucket=${S3_INTEGRATION_BUCKET}"
+#          -var="ssh_key_name=${KEY_NAME}" &&
+#          LOCAL_STACK_HOST_NAME=$(terraform output -raw public_dns) &&
+#          echo $LOCAL_STACK_HOST_NAME &&
+#          echo "::set-output name=local_stack_host_name::$LOCAL_STACK_HOST_NAME" &&
+#          aws s3 cp terraform.tfstate s3://${S3_INTEGRATION_BUCKET}/integration-test/local-stack-terraform-state/${GITHUB_SHA}/terraform.tfstate
   
   # EC2NvidiaGPUIntegrationTest:
   #   needs: [ MakeBinary, BuildMSI, StartLocalStack, GenerateTestMatrix ]
@@ -630,75 +630,75 @@ jobs:
           retry_wait_seconds: 5
           command: cd terraform/ec2/linux && terraform destroy --auto-approve
 
-  EC2WinIntegrationTest:
-    needs: [BuildMSI, GenerateTestMatrix]
-    name: 'EC2WinIntegrationTest'
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        arrays: ${{ fromJson(needs.GenerateTestMatrix.outputs.ec2_windows_matrix) }}
-    permissions:
-      id-token: write
-      contents: read
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          repository: ${{env.CWA_GITHUB_TEST_REPO_NAME}}
-          ref: ${{env.CWA_GITHUB_TEST_REPO_BRANCH}}
-
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
-          aws-region: us-west-2
-
-      # - name: Cache if success
-      #   id: ec2-win-integration-test
-      #   uses: actions/cache@v3
-      #   with:
-      #     path: go.mod
-      #     key: ec2-win-integration-test-${{ github.sha }}-${{ matrix.arrays.os }}-${{ matrix.arrays.arc }}-${{ matrix.arrays.test_dir }}
-
-      - name: Echo OS
-        run: echo run on ec2 instance os ${{ matrix.arrays.os }}
-
-      - name: Verify Terraform version
-        run: terraform --version
-
-        # nick-fields/retry@v2 starts at base dir
-      - name: Terraform apply
-        if: steps.ec2-win-integration-test.outputs.cache-hit != 'true'
-        uses: nick-fields/retry@v2
-        with:
-          max_attempts: 1
-          timeout_minutes: 60
-          retry_wait_seconds: 5
-          command: |
-            cd terraform/ec2/win
-            terraform init
-            if terraform apply --auto-approve \
-            -var="ec2_instance_type=${{ matrix.arrays.instanceType }}" \
-            -var="ssh_key_value=${PRIVATE_KEY}" -var="ssh_key_name=${KEY_NAME}"  \
-            -var="test_name=${{ matrix.arrays.os }}" \
-            -var="cwa_github_sha=${GITHUB_SHA}"  \
-            -var="test_dir=${{ matrix.arrays.test_dir }}" \
-            -var="ami=${{ matrix.arrays.ami }}" \
-            -var="s3_bucket=${S3_INTEGRATION_BUCKET}" ; then
-              terraform destroy -auto-approve
-            else
-              terraform destroy -auto-approve && exit 1
-            fi
-
-      #This is here just in case workflow cancel
-      - name: Terraform destroy
-        if: ${{ cancelled() || failure() }}
-        uses: nick-fields/retry@v2
-        with:
-          max_attempts: 3
-          timeout_minutes: 8
-          retry_wait_seconds: 5
-          command: cd terraform/ec2/win && terraform destroy --auto-approve
+#  EC2WinIntegrationTest:
+#    needs: [BuildMSI, GenerateTestMatrix]
+#    name: 'EC2WinIntegrationTest'
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        arrays: ${{ fromJson(needs.GenerateTestMatrix.outputs.ec2_windows_matrix) }}
+#    permissions:
+#      id-token: write
+#      contents: read
+#    steps:
+#      - uses: actions/checkout@v2
+#        with:
+#          repository: ${{env.CWA_GITHUB_TEST_REPO_NAME}}
+#          ref: ${{env.CWA_GITHUB_TEST_REPO_BRANCH}}
+#
+#      - name: Configure AWS Credentials
+#        uses: aws-actions/configure-aws-credentials@v1
+#        with:
+#          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
+#          aws-region: us-west-2
+#
+#      # - name: Cache if success
+#      #   id: ec2-win-integration-test
+#      #   uses: actions/cache@v3
+#      #   with:
+#      #     path: go.mod
+#      #     key: ec2-win-integration-test-${{ github.sha }}-${{ matrix.arrays.os }}-${{ matrix.arrays.arc }}-${{ matrix.arrays.test_dir }}
+#
+#      - name: Echo OS
+#        run: echo run on ec2 instance os ${{ matrix.arrays.os }}
+#
+#      - name: Verify Terraform version
+#        run: terraform --version
+#
+#        # nick-fields/retry@v2 starts at base dir
+#      - name: Terraform apply
+#        if: steps.ec2-win-integration-test.outputs.cache-hit != 'true'
+#        uses: nick-fields/retry@v2
+#        with:
+#          max_attempts: 1
+#          timeout_minutes: 60
+#          retry_wait_seconds: 5
+#          command: |
+#            cd terraform/ec2/win
+#            terraform init
+#            if terraform apply --auto-approve \
+#            -var="ec2_instance_type=${{ matrix.arrays.instanceType }}" \
+#            -var="ssh_key_value=${PRIVATE_KEY}" -var="ssh_key_name=${KEY_NAME}"  \
+#            -var="test_name=${{ matrix.arrays.os }}" \
+#            -var="cwa_github_sha=${GITHUB_SHA}"  \
+#            -var="test_dir=${{ matrix.arrays.test_dir }}" \
+#            -var="ami=${{ matrix.arrays.ami }}" \
+#            -var="s3_bucket=${S3_INTEGRATION_BUCKET}" ; then
+#              terraform destroy -auto-approve
+#            else
+#              terraform destroy -auto-approve && exit 1
+#            fi
+#
+#      #This is here just in case workflow cancel
+#      - name: Terraform destroy
+#        if: ${{ cancelled() || failure() }}
+#        uses: nick-fields/retry@v2
+#        with:
+#          max_attempts: 3
+#          timeout_minutes: 8
+#          retry_wait_seconds: 5
+#          command: cd terraform/ec2/win && terraform destroy --auto-approve
 
   # EC2DarwinIntegrationTest:
   #   needs: [MakeMacPkg, EC2LinuxIntegrationTest, GenerateTestMatrix]
@@ -769,40 +769,40 @@ jobs:
   #         retry_wait_seconds: 5
   #         command: cd terraform/ec2/mac && terraform destroy --auto-approve
 
-  StopLocalStack:
-    name: 'StopLocalStack'
-    runs-on: ubuntu-latest
-    if: ${{ always() }}
-    needs: [ StartLocalStack, EC2LinuxIntegrationTest ]
-    defaults:
-      run:
-        working-directory: terraform/ec2/localstack
-    permissions:
-      id-token: write
-      contents: read
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          repository: ${{env.CWA_GITHUB_TEST_REPO_NAME}}
-          ref: ${{env.CWA_GITHUB_TEST_REPO_BRANCH}}
-
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
-          aws-region: us-west-2
-
-      - name: Copy state
-        run: aws s3 cp s3://${S3_INTEGRATION_BUCKET}/integration-test/local-stack-terraform-state/${GITHUB_SHA}/terraform.tfstate .
-
-      - name: Verify Terraform version
-        run: terraform --version
-
-      - name: Terraform init
-        run: terraform init
-
-      - name: Terraform destroy
-        run: terraform destroy --auto-approve
+#  StopLocalStack:
+#    name: 'StopLocalStack'
+#    runs-on: ubuntu-latest
+#    if: ${{ always() }}
+#    needs: [ StartLocalStack, EC2LinuxIntegrationTest ]
+#    defaults:
+#      run:
+#        working-directory: terraform/ec2/localstack
+#    permissions:
+#      id-token: write
+#      contents: read
+#    steps:
+#      - uses: actions/checkout@v3
+#        with:
+#          repository: ${{env.CWA_GITHUB_TEST_REPO_NAME}}
+#          ref: ${{env.CWA_GITHUB_TEST_REPO_BRANCH}}
+#
+#      - name: Configure AWS Credentials
+#        uses: aws-actions/configure-aws-credentials@v2
+#        with:
+#          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
+#          aws-region: us-west-2
+#
+#      - name: Copy state
+#        run: aws s3 cp s3://${S3_INTEGRATION_BUCKET}/integration-test/local-stack-terraform-state/${GITHUB_SHA}/terraform.tfstate .
+#
+#      - name: Verify Terraform version
+#        run: terraform --version
+#
+#      - name: Terraform init
+#        run: terraform init
+#
+#      - name: Terraform destroy
+#        run: terraform destroy --auto-approve
 
   # ECSEC2IntegrationTest:
   #   name: 'ECSEC2IntegrationTest'
